// <auto-generated />
using System;
using BorgerSvar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BorgerSvar.Infrastructure.Migrations
{
    [DbContext(typeof(BorgerSvarDbContext))]
    [Migration("20260609143629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BorgerSvar.Domain.CitizenQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CitizenQueries");
                });

            modelBuilder.Entity("BorgerSvar.Domain.CitizenQuery", b =>
                {
                    b.OwnsOne("BorgerSvar.Domain.CitizenIdCard", "CitizenIdCard", b1 =>
                        {
                            b1.Property<Guid>("CitizenQueryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Citizen_Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Citizen_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Citizen_LastName");

                            b1.HasKey("CitizenQueryId");

                            b1.ToTable("CitizenQueries");

                            b1.WithOwner()
                                .HasForeignKey("CitizenQueryId");
                        });

                    b.Navigation("CitizenIdCard")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
